# Generated by Django 2.2.4 on 2019-08-09 13:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agotboardgame_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeringame',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
