# Generated by Django 3.0.2 on 2020-01-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agotboardgame_main', '0002_playeringame_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeringame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='agotboardgame_main.Game'),
        ),
    ]
