# Generated by Django 3.0.2 on 2020-02-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agotboardgame_main', '0004_create_public_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'permissions': [('can_play_as_another_player', 'Can impersonate an other player in a game')]},
        ),
    ]
