# Generated by Django 3.0.2 on 2020-02-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agotboardgame_main', '0005_auto_20200212_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_username_update_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
