# Generated by Django 3.0.2 on 2020-03-16 13:04
from django.conf import settings
from django.contrib.auth.models import Group
from django.db import migrations

from agotboardgame_main.models import User


def forward(apps, schema_editor):
    group = Group.objects.get(name=settings.DEFAULT_GROUP)

    for user in User.objects.all():
        group.user_set.add(user)


def reverse(apps, schema_editor):
    # Too lazy to actually code this, no-one's gonna use it anyway.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('agotboardgame_main', '0007_auto_20200227_1400'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
