# Generated by Django 3.0.2 on 2020-03-19 19:12

import agotboardgame_main.models
import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agotboardgame_main', '0008_auto_20200316_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='view_of_game',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=agotboardgame_main.models.generate_default_view_of_game, null=True),
        ),
    ]
