# Generated by Django 3.0.2 on 2020-03-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agotboardgame_main', '0010_auto_20200319_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'permissions': [('can_play_as_another_player', 'Can impersonate an other player in a game'), ('cancel', 'Can cancel a game')]},
        ),
    ]
