# Generated by Django 3.0.2 on 2020-04-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agotboardgame_main', '0012_auto_20200324_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notification_active',
            field=models.BooleanField(default=True),
        ),
    ]
