# Generated by Django 3.0.2 on 2021-08-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agotboardgame_main', '0014_user_vanilla_forum_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mute_games',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='use_house_names_for_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='use_map_scrollbar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='use_responsive_layout_on_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
