# Generated by Django 3.0.2 on 2022-01-26 10:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
from agotboardgame_main.models import Game
import uuid


class Migration(migrations.Migration):
    def reset_last_active_at_to_updated_at(apps, schema_editor):
        # Repeat it as I forgot to save
        for game in Game.objects.all():
            game.last_active_at = game.updated_at
            game.save()

    def reverse(apps, schema_editor):
        # Too lazy to actually code this, no-one's gonna use it anyway.
        pass

    dependencies = [
        ('agotboardgame_main', '0017_game_last_active_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PbemResponseTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('response_time', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(reset_last_active_at_to_updated_at, reverse)
    ]
