# Generated by Django 3.0.2 on 2023-02-18 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agotboardgame_main', '0019_reset_use_house_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_text',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_won_tournament',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        )
    ]
